# Note New Lines in Queries are not supported in this editor.
# Authorization: Basic <SOME_USER_PASSWORD>
###

POST http://localhost:8080/bingo/api/graphql HTTP/1.1
X-Request-Type: GraphQL

query{
    ping
    pingAdmin
}

###

POST http://localhost:8080/bingo/api/graphql HTTP/1.1
X-Request-Type: GraphQL

query{
    admin {
        currentSessions
    }
}

###

POST http://localhost:8080/bingo/api/graphql HTTP/1.1
X-Request-Type: GraphQL
Authorization: Basic <SOME_USER_PASSWORD>

query{
    labelPing1: ping
    labelPing2: ping
    pingAdmin
}

###

POST http://localhost:8080/bingo/api/graphql HTTP/1.1
X-Request-Type: GraphQL
Authorization: Basic <SOME_USER_PASSWORD>

mutation {
    admin {
        republishStatus
    }
}

###

POST http://localhost:8080/bingo/api/graphql HTTP/1.1
X-Request-Type: GraphQL
Authorization: Basic <SOME_USER_PASSWORD>

mutation CreatePool ($termPool:   [TermPoolCategoryInput!]!) {
    admin {
        updateTermPool(input: {categories: $termPool, replace: true})
    }
}

{
    "termPool": [
             {
            "category": "uiux-secret",
            "terms": [
                "Dreilochstute"
            ]
             },
                          {
            "category": "fax-secret",
            "terms": [
                "Gladiator"
            ]
             },
        {
            "category": "general",
            "terms": [
                "zero tolerance",
                "Synergistic",
                "firmware",
                "actuating",
                "adapter",
                "Cloned",
                "zero defect",
                "internet solution",
                "Cloned",
                "ability",
                "Universal",
                "project",
                "real-time",
                "web-enabled",
                "superstructure",
                "leverage",
                "composite",
                "architecture",
                "heuristic",
                "hierarchy",
                "methodology",
                "Phased",
                "capability",
                "radical",
                "User-centric",
                "neutral",
                "Upgradable",
                "Synchronised",
                "software",
                "Progressive",
                "pricing structure",
                "architecture",
                "throughput",
                "analyzer",
                "open architecture",
                "Robust",
                "neural-net",
                "3rd generation",
                "data-warehouse",
                "Inverse",
                "capability",
                "functionalities",
                "Multi-channelled",
                "next generation",
                "tangible",
                "implementation",
                "exuding"
            ]
        },
        {
            "category": "edi",
            "terms": [
                "strategy",
                "extranet",
                "Implemented",
                "challenge",
                "uniform",
                "Object-based",
                "dynamic",
                "groupware",
                "Function-based",
                "Exclusive",
                "Enterprise-wide",
                "model",
                "Profit-focused",
                "Synchronised",
                "impactful",
                "Team-oriented",
                "Pre-emptive",
                "Networked",
                "Proactive",
                "foreground",
                "hub",
                "access",
                "time-frame",
                "composite",
                "Optional",
                "web-enabled",
                "human-resource",
                "budgetary management",
                "structure",
                "dedicated",
                "strategy",
                "Implemented",
                "Enterprise-wide",
                "alliance",
                "directional",
                "uniform",
                "methodology",
                "local",
                "instruction set",
                "Object-based",
                "Operative",
                "cohesive",
                "Upgradable",
                "Polarised",
                "client-driven",
                "tertiary",
                "infrastructure",
                "homogeneous"
            ]
        },
        {
            "category": "fax",
            "terms": [
                "homogeneous",
                "background",
                "Switchable",
                "multi-tasking",
                "Monitored",
                "5th generation",
                "success",
                "eco-centric",
                "Reverse-engineered",
                "tertiary",
                "throughput",
                "non-volatile",
                "Stand-alone",
                "Assimilated",
                "architecture",
                "protocol",
                "Face to face",
                "local area network",
                "cohesive",
                "Configurable",
                "product",
                "zero defect",
                "frame",
                "function",
                "Phased",
                "holistic",
                "zero administration",
                "synergy",
                "firmware",
                "explicit",
                "Profit-focused",
                "Synergistic",
                "Decentralized"
            ]
        },
        {
            "category": "sms",
            "terms": [
                "Robust",
                "functionalities",
                "Multi-channelled",
                "collaboration",
                "Reactive",
                "intangible",
                "orchestration",
                "systematic",
                "moratorium",
                "4th generation",
                "real-time",
                "Reverse-engineered",
                "intermediate",
                "portal",
                "Enterprise-wide",
                "reciprocal",
                "solution",
                "Cross-platform",
                "hybrid",
                "budgetary management",
                "tertiary",
                "challenge",
                "Virtual",
                "static",
                "impactful",
                "Customizable",
                "protocol",
                "superstructure",
                "firmware",
                "framework",
                "needs-based",
                "secondary",
                "architecture",
                "core",
                "Polarised",
                "interactive",
                "intermediate",
                "homogeneous",
                "leading edge",
                "model",
                "open system",
                "User-centric",
                "background",
                "object-oriented",
                "Fully-configurable",
                "Ergonomic",
                "budgetary management"
            ]
        },
        {
            "category": "emailsec",
            "terms": [
                "migration",
                "explicit",
                "optimal",
                "motivating",
                "Pre-emptive",
                "help-desk",
                "Face to face",
                "moratorium",
                "Triple-buffered",
                "Adaptive",
                "Re-contextualized",
                "tangible",
                "web-enabled",
                "scalable",
                "Reactive",
                "Phased",
                "orchestration",
                "Organic",
                "methodical",
                "interface",
                "utilisation",
                "methodical",
                "approach",
                "Implemented",
                "system-worthy",
                "internet solution",
                "Centralized",
                "ability",
                "well-modulated",
                "methodical",
                "Multi-channelled",
                "dedicated",
                "matrix",
                "local",
                "motivating",
                "matrices",
                "Team-oriented",
                "local",
                "directional",
                "moratorium",
                "attitude-oriented",
                "mission-critical",
                "even-keeled",
                "secondary"
            ]
        },
        {
            "category": "uiux",
            "terms": [
                "grid-enabled",
                "Distributed",
                "incremental",
                "disintermediate",
                "multi-state",
                "systematic",
                "infrastructure",
                "protocol",
                "Operative",
                "neutral",
                "explicit",
                "Organized",
                "synergy",
                "toolset",
                "local",
                "Enhanced",
                "systemic",
                "user-facing",
                "Distributed",
                "explicit",
                "definition",
                "knowledge base",
                "tertiary",
                "high-level",
                "Public-key",
                "interface",
                "task-force",
                "Ameliorated",
                "open system",
                "Inverse"
            ]
        }
    ]
}

###

POST http://localhost:8080/bingo/api/graphql HTTP/1.1
X-Request-Type: GraphQL

mutation {
    createCard(input: { owner: "Jens1"}) {
        cardId
        createdAt
        cardOwner
        terms
    }
}