version: '2'
services:
    bingo-app-webapp:
        upgrade_strategy:
            start_first: true
        scale: 1
        start_on_create: true
        health_check:
            healthy_threshold: 2
            response_timeout: 2000
            recreate_on_quorum_strategy_config:
                quorum: 1
            port: 80
            unhealthy_threshold: 3
            initializing_timeout: 10000
            interval: 2000
            strategy: recreateOnQuorum
            request_line: GET "/favicon.ico" "HTTP/1.0"
            reinitializing_timeout: 10000
